- name: sshd config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: restart sshd service
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false